### ISSUE TITLE
can i set the target ip scanning port ?

### ISSUE THREAD

**Issue by contigon** [Ostorlab/agent_asteroid#130]
can i set the target ip scanning port ?

**Comment by 3asm** [comment]
@contigon the asteroid agent typically work in tandem with another network scanning agent like https://github.com/ostorlab/agent_nmap/ (Nmap).

You can specify the ports for `Nmap` and `Asteroid` agent will scan them if the service is found to be up:

```shell
oxo scan run --instal --agent nmap --agent asteroid --arg "port:8080" ip 1.2.3.4
```
